### ISSUE TITLE
Faulty line in the setup function

### ISSUE THREAD

**Issue by majuss** [MajenkoLibraries/TLV320DAC3101#2]
Line 52 in TLV320DAC3101.cpp:
```c++
setRegister(1, 0x1f, 0b000010100);
```
Tries to set the headphone driver, but it has 9 bits instead of 8. Line 59 also sets the headphone driver in the correct way with 8 bits. So I'am very confused about line 52, or am I mssing something :D?

**Comment by majenkotech** [comment]
Both lines are slightly wrong, each in their own way.  Line 52 is just semantics. Like in normal decimal numbers leading zeros are ignored. `0b10100` and `0b0000000000000000010100` are the same thing.  Line 59 should actually be `0b11010100`.  

52 configures the headphone driver to the right voltage, and 59 turns it on.
