### ISSUE TITLE
Which hardware do you use?

### ISSUE THREAD

**Issue by majuss** [MajenkoLibraries/TLV320DAC3101#3]
Hi there, I guess you're using some chipKit development Board? But what breakout do you use for the DAC? And how do I connect all of that? I'am trying to use the DAC with an ESP32, is only the MCLK sufficient or do I need BCLK and MCLK? Thank you for your help :=)

**Comment by majenkotech** [comment]
I don't use a breakout. It's embedded in a custom PCB.

You need all three clocks - MCLK for the master supersampling frequency (usually sample greq * 256 IIRC), BCLK for the data communication (it's like SCK for SPI) and WCLK (or is it LRCLK?) to synchgronise the left/right words. None are optional.

Note: this library is only for the control (I2C interface) of the DAC. The actual audio is generated as a standard I2S stream using another library.

**Comment by majuss** [comment]
Thank you! Is this PCB openly available? Which library do you use for the I2S?

**Comment by majenkotech** [comment]
No, it's not really available. It's an entire system with lots of other hardware, including a TFT screen. It looks like this:

![](https://i.redd.it/qpswfm78gdf21.png)

The I2S library is https://github.com/MajenkoLibraries/I2S however it won't be of much use to you as it's pretty much all PIC32 specific register coding for the I2S interface and DMA transfers of data.

**Comment by majuss** [comment]
Really cool project!
